import streamlit as st

from data_gen.generator import END_DATE, START_DATE, load_data
from theme.charts import register_template
from theme.style import inject_css, kpi_grid, section_header

st.set_page_config(
    page_title="PixFlow Analytics",
    layout="wide",
    page_icon="💠",
    initial_sidebar_state="expanded",
)
inject_css()
register_template()

section_header("👋", "About the Author")

col_bio, col_links = st.columns([2.2, 1])
with col_bio:
    st.markdown(
        "**Lucas Bastos** — Data Analyst focused on ETL, data modeling and revenue analytics. "
        "Currently the first data hire at a crypto-payments fintech, building pipelines and "
        "dashboards for PIX, crypto and banking transactions from the ground up; previously in "
        "EdTech planning/forecasting and manufacturing BI. This app is a portfolio piece built to "
        "showcase that kind of work end-to-end — data generation, modeling, and dashboard design — "
        "with fully synthetic and anonymized data (see the disclaimer below)."
    )
with col_links:
    st.link_button("LinkedIn", "https://www.linkedin.com/in/lucas-bastos-56756084/", use_container_width=True)
    st.link_button("GitHub", "https://github.com/lucasboliv-coder", use_container_width=True)
    st.link_button("Email", "mailto:lucasboliv@gmail.com", use_container_width=True)

st.markdown("---")

st.title("💠 PixFlow Analytics — PixFlow & NovaPay Finance")
st.markdown(
    "Data Analyst portfolio project — product and financial dashboards for two fictional "
    "companies of a payments/crypto fintech group, **PixFlow** and **NovaPay Finance**."
)

st.info(
    "🔒 **No real data in the product dashboards.** PixFlow is a fictional "
    "brand created for this portfolio. Users, transactions and volumes in the "
    "Users, PIX and Blockchain dashboards are 100% synthetic, generated by a "
    "deterministic script (`data_gen/generator.py`). The **Financial "
    "Projections** dashboard is the one exception: it's derived from real "
    "multi-year financial models I built professionally for two companies of "
    "a payments/fintech group. Company names are fictionalized, and every "
    "figure has been scaled by an undisclosed per-company factor before "
    "publishing — growth rates and cost/revenue ratios closely track the "
    "real model (aside from rounding), the absolute numbers do not — see "
    "that page for details.",
    icon="🔒",
)

data = load_data()
users = data["users"]
pix_in, pix_out = data["pix_in"], data["pix_out"]
chain = data["chain"]

section_header("📊", "Synthetic dataset overview")

pix_volume = pix_in["amount_brl"].sum() + pix_out["amount_brl"].sum()
chain_volume = chain["value"].sum()
total_transactions = len(pix_in) + len(pix_out) + len(chain)

kpi_grid(
    [
        {"icon": "👥", "label": "Registered users", "value": f"{len(users):,}"},
        {"icon": "💸", "label": "PIX volume (in + out)", "value": f"R$ {pix_volume:,.0f}"},
        {"icon": "🔗", "label": "On-chain volume", "value": f"{chain_volume:,.0f}"},
        {"icon": "🧾", "label": "Total transactions", "value": f"{total_transactions:,}"},
    ]
)

st.markdown(f"**Simulated period:** {START_DATE:%m/%d/%Y} — {END_DATE:%m/%d/%Y}")

section_header("🧭", "Dashboards")

col1, col2, col3, col4 = st.columns(4)
with col1:
    st.markdown("#### 👥 Users & Avg Ticket")
    st.markdown(
        "Active user growth, monthly/yearly matrix and average ticket "
        "trend by direction (in/out)."
    )
    st.page_link("pages/1_👥_Users_and_Ticket.py", label="Open dashboard", icon="👥")
with col2:
    st.markdown("#### 💸 PIX In / Out")
    st.markdown(
        "Volume, fees, status and value×fee correlation for incoming and "
        "outgoing PIX transactions."
    )
    st.page_link("pages/2_💸_Pix_In_Out.py", label="Open dashboard", icon="💸")
with col3:
    st.markdown("#### 🔗 Blockchain")
    st.markdown(
        "On-chain and bridge activity, by symbol, with year-over-year "
        "comparison and status analysis."
    )
    st.page_link("pages/3_🔗_Blockchain.py", label="Open dashboard", icon="🔗")
with col4:
    st.markdown("#### 📈 Financial Projections")
    st.markdown(
        "Revenue, costs and client growth for the group's two companies, "
        "projected through 2029 across 3 scenarios. *(anonymized real data)*"
    )
    st.page_link("pages/4_📈_Financial_Projections.py", label="Open dashboard", icon="📈")

st.markdown("---")
st.caption(
    "Stack: Streamlit + Plotly + pandas/numpy. "
    "[Source code on GitHub](https://github.com/lucasboliv-coder/pix-analytics-portfolio)."
)
